# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DDwIc5TWT5unjjS/nsRmOPRsyWpjTsWeicdiom21u6ZTJJPsyPtr/lWTEuhri2oCjzO1KM4zQd86/opvfcyKxWSWvejqijAScZmcToseIcqguOHv19PLHpaJlaBtoIu+R2IkP7V+j0tb2OYZWXBm8oviXaz8JOvep/7JOTPXf5nogFGM6EMNJlpN9fYm3QNvDjrdJ8hQEY4+V+rmJueym0MnmlgVXzLmswVSGFBIDvym+efqf/krveaGECrmDbnU7DaZr0pJ1UlSPPlTk0NYY1V5U3a2ls79kjbuXkYI9uXu9DcnGCZ1cnjXYafRAv1Ba3dOxotE5Xu0KHkvMo6HeRosklp+YA2/yRTRWO/3iwVRS/LX68xIKzhVfmm501CiQN4nxVEvUrkELIHDOJLuFaooF8mHjjZQM8fK1J/ig5EcycNdjWlk/eawg7BdQFoBDaFgp9CbwBk1+pWQbGFAvGZBsuleMzM/WP1hnKbYeZVrf7+mYctLIXURXAON/nWEhMuEji2sMsK4iVDdb18+R2tRm/oKQYzjMGN7pXYDiT3+h8CHOpK3P2b+qWMLeJgMTHVWCWN1XpAUnPZZPRwv+eWJXe/wlof922fbFPN+FctgUPceUljGvDm36THpat2EZMZbqAxw39hM1L+ZRUQvvXdgWNPwGhcZm6oXKJgUlQY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml