appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DDwIc5TWT5unjjS/nsRmOPRsyWpjTsWeicdiom21u6ZTJJPsyPtr/lWTEuhri2oCjzO1KM4zQd86/opvfcyKxWSWvejqijAScZmcToseIcqguOHv19PLHpaJlaBtoIu+R2IkP7V+j0tb2OYZWXBm8oviXaz8JOvep/7JOTPXf5nogFGM6EMNJlpN9fYm3QNvDjrdJ8hQEY4+V+rmJueym0MnmlgVXzLmswVSGFBIDvym+efqf/krveaGECrmDbnU7DaZr0pJ1UlSPPlTk0NYY1V5U3a2ls79kjbuXkYI9uXu9DcnGCZ1cnjXYafRAv1Ba3dOxotE5Xu0KHkvMo6HeRosklp+YA2/yRTRWO/3iwVRS/LX68xIKzhVfmm501CiQN4nxVEvUrkELIHDOJLuFaooF8mHjjZQM8fK1J/ig5EcycNdjWlk/eawg7BdQFoBDaFgp9CbwBk1+pWQbGFAvGZBsuleMzM/WP1hnKbYeZVrf7+mYctLIXURXAON/nWEhMuEji2sMsK4iVDdb18+R2tRm/oKQYzjMGN7pXYDiT3+h8CHOpK3P2b+qWMLeJgMTHVWCWN1XpAUnPZZPRwv+eWJXe/wlof922fbFPN+FctgUPceUljGvDm36THpat2EZMZbqAxw39hM1L+ZRUQvvXdgWNPwGhcZm6oXKJgUlQY=}
